# Generated by Django 5.0.6 on 2025-04-28 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0002_otpstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('milk_quantity_liters', models.FloatField()),
                ('procurement_date', models.DateField()),
                ('plant_location', models.CharField(max_length=100)),
                ('price_per_liter', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MilkVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=50)),
                ('price_per_liter', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NandiniShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('weekly_demand_liters', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_batch_number', models.CharField(max_length=20)),
                ('quality_check_date', models.DateField()),
                ('quality_status', models.CharField(max_length=50)),
                ('storage_facility', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('capacity_liters', models.FloatField()),
                ('driver_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='milkorder',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='milkorder',
            name='product',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_quantity_liters', models.FloatField()),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milkapp.nandinishop')),
            ],
        ),
        migrations.CreateModel(
            name='PricingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('subsidy', models.FloatField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milkapp.milkvariant')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('route', models.TextField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milkapp.nandinishop')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milkapp.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
        migrations.DeleteModel(
            name='MilkOrder',
        ),
        migrations.DeleteModel(
            name='MilkProduct',
        ),
    ]
