# Generated by Django 5.0.6 on 2025-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0003_milkproduction_milkvariant_nandinishop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkvariant',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
