# Generated by Django 5.0.6 on 2025-04-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0004_milkvariant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
